### ISSUE TITLE
No Way to Build Jar File

### ISSUE THREAD

**Issue by gungwald** [andrew-jacobs/dev65#1]
Ideally, one should be able to clone the repo and then type "ant" or "mvn package" to get an executable jar file, like dev65.jar. 65xx.zip is not such a good name. Java classes should go into a jar file not a zip file. The 65xx part doesn't communicate the name of the application, which is dev65.

Unless you install Eclipse there is no way to build it. Eclipse can generate an Ant script. That would be nice. Maven would be better. Even with Eclipse, the 65xx.zip file won't be generated automatically.

**Comment by BigEd** [comment]
Sadly, Andrew [passed away earlier this month](http://forum.6502.org/viewtopic.php?f=1&t=6466).

It would be great if you could bring your fork up to date and add a built file as a Release, or in any other way help people build a runnable version of this project.   I've tried building from source but I don't know what I'm doing. I'm prepared to use a command line... (There's a thread [here](http://forum.6502.org/viewtopic.php?p=81552#p81552) looking for guidance, which brought me here in an effort to help.)

```
$ sudo port install openjdk14
$ sudo port install apache-ant
$ ant
Buildfile: /Users/ed/github/dev65-andrew-jacobs/build.xml

build-subprojects:

init:
    [mkdir] Created dir: /Users/ed/github/dev65-andrew-jacobs/bin
     [copy] Copying 72 files to /Users/ed/github/dev65-andrew-jacobs/bin

build-project:
     [echo] Dev65: /Users/ed/github/dev65-andrew-jacobs/build.xml
    [javac] Compiling 136 source files to /Users/ed/github/dev65-andrew-jacobs/bin
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 6
    [javac] error: Source option 6 is no longer supported. Use 7 or later.
    [javac] error: Target option 6 is no longer supported. Use 7 or later.

```

**Comment by BigEd** [comment]
(Tagging @gungwald )

**Comment by gungwald** [comment]
I just now saw this. I am sorry. That is very sad to hear. He died on my 52nd birthday. Damn COVID. Yes, I can make it build and I have thought of some additional improvements, like making labels work properly inside macros. Everything works fine in macros if you use the structured assembly syntax, but basic labels are repeated verbatim every time a macro is used, leading to redefinition errors.

**Comment by gungwald** [comment]
v2.0.0 now has a build script, produces an installable artifact and has scripts to invoke the assembler and linker.
